spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanagement?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  
        
management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info
  endpoint:
    health:
      show-details: ALWAYS
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress:true
    