spring:
  datasource:
    initialization-mode: ALWAYS
    url: jdbc:mysql://localhost:3306/notes?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: ALWAYS
        
jwt:
  secret: ashwin
  
info:
  app:
    name: Notes Application
    version : 1.0
    java:
      version: 1.8